<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-LOFBR5SJ" failures="1" tests="3" name="RestAssuredTest" time="7.41" errors="0" timestamp="19 Feb 2024 13:46:57 GMT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.134"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.605"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.319">
    <failure type="java.lang.AssertionError" message="expected [300] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [300] but found [200]
at stepDefinition.ApiTestingStepDef.i_verify_the_status_code_as(ApiTestingStepDef.java:91)
at âœ½.I verify the status code as "300"(file:src/test/resources/features/APITesting_GetOrder.feature:7)
... Removed 5 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- RestAssuredTest -->
